<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>soundlib</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SoundLib.Core\SoundLib.Core.csproj" />
	</ItemGroup>

</Project>
